homebrew_taps:
  - heroku/brew
  - homebrew/bundle
  - homebrew/cask
  - homebrew/core
  - heroku/brew
homebrew_cask_packages:
  - name: adobe-creative-cloud
  - name: alfred
  - name: appcleaner
  # - name: arduino
  - name: balenaetcher
  - name: bartender
  - name: bitwarden
  - name: cyberduck
  - name: db-browser-for-sqlite
  - name: docker
  - name: drawio
  - name: firefox
  - name: fritzing
  - name: google-chrome
  - name: google-japanese-ime
  - name: hyperswitch
  - name: karabiner-elements
  # - name: mutagen-io/mutagen/mutagen
  - name: ngrok
  - name: notable
  - name: notion
  - name: postman
  - name: sequel-pro-nightly
  - name: skitch
  - name: skype
  - name: slack
  - name: startninja
  - name: thunderbird
  - name: vagrant
  - name: virtualbox
  - name: visual-studio-code
  - name: xmind
homebrew_packages:
  - name: ansible
  - name: autoconf
  - name: awscli
  - name: bash-completion
  - name: bitwarden-cli
  - name: cmake
  - name: docker
  - name: git
  - name: heroku
  - name: hub
  - name: jq
  - name: kubernetes-cli
  - name: mas
  - name: minikube
  - name: nkf
  # - name: terraform
  - name: tfenv
  - name: tig
  - name: tmux
  - name: tree
  - name: vim
  - name: wget
dot_files:
  - name: bash_profile
  - name: bashrc
  - name: tmux.conf
  - name: vimrc

